"""Reference requirements and state capture for the isolation instrument (repository route; lineage: candidate v0.4, UFUND-2).

MAINTENANCE: a packet that adds a core migration declares its head in REQUIRED_TRIGGER_COUNT, with the ground for the
count. Until it does, the route reports isolation NOT ESTABLISHED at CP-0 for that head: the declaration is part of the
packet, not an assumption of the route.

v0.3 changes one thing: the schema version is declared, not assumed. The run declares its expected core
migration head in VERIFICATION_EXPECTED_CORE_HEAD; the head must be exactly that (not merely present), and the
required trigger count is looked up for that head. An undeclared or unknown head fails CP-0. Everything else
is unchanged from v0.2.

Checkpoints
  CP-0  after the test runner has created and migrated the test database, before the first test.
        The captured state must first satisfy the DECLARED REQUIREMENTS below; only then is it
        used as the per-test comparison reference.
  CP-A  unittest startTest for each test: after Django's _pre_setup, before the test's own setUp.
Read-only: every query here is a SELECT.
"""
import hashlib
import importlib
import json
import os

from django.db import connection

# ---------------------------------------------------------------- declared requirements
# REQ-T1  every non-internal trigger in the schema is enabled ('O')
#         ground: no migration 0001-0022 disables a trigger or enables one in another mode [D]
# REQ-T2  non-internal trigger count equals REQUIRED_TRIGGER_COUNT for the declared head
#         0022: 322 - D-S015-PKT-A-3 section 7 (0021's 246 + 0022's 76) [S]; U0 runs 2 and 3 observed 322 [O]
#         0023: 322 - 0023 creates and drops no trigger (it replaces two functions and five CHECKs) [D]
#         0024: 322 - 0024 creates and drops no trigger (it replaces two function bodies) [D]
# REQ-G1  the twelve required truncate guardians of the standard backend are present and enabled [D]
# REQ-C1  every constraint named s015_* is validated
#         ground: no migration 0001-0024 creates a constraint NOT VALID [D]
# REQ-D1  core_role holds exactly the rows migration 0003's create_triad_roles defines
#         ground: the migration function itself, executed against a recording stub (values not copied)
# REQ-D2  every other table holds zero rows, except the framework tables below
# REQ-D3  django_content_type and auth_permission are non-empty; their natural keys are
#         framework-generated by post_migrate, so they are compared with CP-0 (declared snapshot use)
# REQ-D4  the latest core migration recorded is exactly the declared head (VERIFICATION_EXPECTED_CORE_HEAD)
# REQ-P1  PUBLIC holds no INSERT privilege on s015_transaction_register
#         ground: 0021 'REVOKE ALL ON public.s015_transaction_register FROM PUBLIC' [D]; the selected
#         test test_neg_non_owner_cannot_write_register relies on it [D]
# OWNERSHIP AND GRANTS: no selected test statically alters grants, ownership or roles (no GRANT,
#         REVOKE, OWNER, SET ROLE or CREATE ROLE in the three suites or their support module) [D];
#         one relies on a privilege (REQ-P1). Table and function owners and ACLs are therefore
#         captured and compared at every CP-A rather than excluded.
# DECLARED EXCLUSIONS (accepted by the Human Governor for this bounded check, 16 Sep 2026):
#         sequence and identity positions; primary keys of framework rows.
# EVIDENCE CLAIM: equality at the compared properties only. NOT complete database-state equivalence.
FRAMEWORK_TABLES = ("django_content_type", "auth_permission")
SEED_TABLES = ("core_role",)
LEDGER_TABLES = ("django_migrations",)
REQUIRED_TRIGGER_COUNT = {"0022_s015_governed_chain_contract": 322, "0023_s015_canonical_form_s015f4": 322,
                          "0024_s015_compact_commitment_preimages": 322}
EXPECTED_HEAD_ENV = "VERIFICATION_EXPECTED_CORE_HEAD"


def _rows(sql, params=None):
    with connection.cursor() as cursor:
        cursor.execute(sql, params)
        return [tuple(r) for r in cursor.fetchall()]


def expected_seed_rows():
    """Run 0003's own seed function against a stub that records what it would create."""
    recorded = []

    class _Manager:
        def get_or_create(self, **kwargs):
            defaults = kwargs.pop("defaults", {})
            recorded.append(tuple(sorted({**kwargs, **defaults}.items())))
            return None, True

    class _Model:
        objects = _Manager()

    class _Apps:
        def get_model(self, app_label, model_name):
            return _Model

    module = importlib.import_module("core.migrations.0003_seed_triad_roles")
    module.create_triad_roles(_Apps(), None)
    return sorted(recorded)


def capture():
    s = {}
    s["triggers"] = _rows(
        """SELECT c.relname, t.tgname, t.tgenabled, t.tgtype, p.proname, md5(p.prosrc)
           FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid
           JOIN pg_namespace n ON n.oid = c.relnamespace JOIN pg_proc p ON p.oid = t.tgfoid
           WHERE n.nspname = current_schema() AND NOT t.tgisinternal ORDER BY 1, 2""")
    s["constraints"] = _rows(
        """SELECT c.relname, co.conname, co.contype, co.convalidated, pg_get_constraintdef(co.oid)
           FROM pg_constraint co JOIN pg_class c ON c.oid = co.conrelid
           JOIN pg_namespace n ON n.oid = c.relnamespace
           WHERE n.nspname = current_schema() ORDER BY 1, 2""")
    s["ownership_grants"] = _rows(
        """SELECT 'table', c.relname, pg_get_userbyid(c.relowner), coalesce(c.relacl::text, '')
           FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
           WHERE n.nspname = current_schema() AND c.relkind IN ('r', 'p', 'v', 'S')
           UNION ALL
           SELECT 'function', p.proname || '(' || pg_get_function_identity_arguments(p.oid) || ')',
                  pg_get_userbyid(p.proowner), coalesce(p.proacl::text, '')
           FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
           WHERE n.nspname = current_schema() ORDER BY 1, 2""")
    s["public_register_insert"] = _rows(
        "SELECT has_table_privilege('public', 'public.s015_transaction_register', 'INSERT')")[0][0]
    s["functions"] = _rows(
        """SELECT p.proname, pg_get_function_identity_arguments(p.oid), md5(p.prosrc), p.prosecdef, p.provolatile
           FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
           WHERE n.nspname = current_schema() ORDER BY 1, 2""")
    tables = [r[0] for r in _rows(
        """SELECT c.relname FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
           WHERE n.nspname = current_schema() AND c.relkind IN ('r', 'p') ORDER BY 1""")]
    counts = {}
    with connection.cursor() as cursor:
        for t in tables:
            cursor.execute('SELECT count(*) FROM "%s"' % t.replace('"', '""'))
            counts[t] = cursor.fetchone()[0]
    s["row_counts"] = counts
    s["core_role"] = sorted(
        tuple(sorted({"name": n, "description": d}.items()))
        for n, d in _rows("SELECT name, description FROM core_role"))
    s["content_types"] = _rows("SELECT app_label, model FROM django_content_type ORDER BY 1, 2")
    s["permissions"] = _rows(
        """SELECT ct.app_label, ct.model, p.codename FROM auth_permission p
           JOIN django_content_type ct ON ct.id = p.content_type_id ORDER BY 1, 2, 3""")
    s["migrations"] = _rows("SELECT app, name FROM django_migrations ORDER BY 1, 2")
    return s


def digest(value):
    return hashlib.sha256(json.dumps(value, sort_keys=True, default=str).encode("utf-8")).hexdigest()


def check_requirements(s, required_guardians):
    """CP-0 requirements. Returns a list of violations (empty = requirements met)."""
    v = []
    disabled = [(t, n, e) for t, n, e, _, _, _ in s["triggers"] if e != "O"]
    if disabled:
        v.append("REQ-T1 triggers not enabled: %s" % disabled[:10])
    head = os.environ.get(EXPECTED_HEAD_ENV)
    if head not in REQUIRED_TRIGGER_COUNT:
        v.append("REQ-D4 expected core head %r is not declared or not known to this instrument" % head)
    elif len(s["triggers"]) != REQUIRED_TRIGGER_COUNT[head]:
        v.append("REQ-T2 trigger count %d, required %d at %s" % (len(s["triggers"]), REQUIRED_TRIGGER_COUNT[head], head))
    present = {(t, n): e for t, n, e, _, _, _ in s["triggers"]}
    for table, name in required_guardians.items():
        if present.get((table, name)) != "O":
            v.append("REQ-G1 required guardian missing or disabled: %s.%s" % (table, name))
    invalid = [(t, n) for t, n, _, ok, _ in s["constraints"] if n.startswith("s015_") and not ok]
    if invalid:
        v.append("REQ-C1 s015 constraints not validated: %s" % invalid[:10])
    expected = expected_seed_rows()
    if s["core_role"] != expected:
        v.append("REQ-D1 core_role rows %s, required %s" % (s["core_role"], expected))
    nonempty = {t: c for t, c in s["row_counts"].items()
                if c and t not in FRAMEWORK_TABLES + SEED_TABLES + LEDGER_TABLES}
    if nonempty:
        v.append("REQ-D2 tables holding rows: %s" % dict(list(nonempty.items())[:15]))
    if not s["content_types"] or not s["permissions"]:
        v.append("REQ-D3 framework tables empty")
    if s["public_register_insert"] is not False:
        v.append("REQ-P1 PUBLIC holds INSERT on s015_transaction_register")
    core = sorted(name for app, name in s["migrations"] if app == "core")
    if head in REQUIRED_TRIGGER_COUNT and (not core or core[-1] != head):
        v.append("REQ-D4 latest core migration %s, declared head %s" % (core[-1] if core else None, head))
    return v


def compare(reference, s, ignore_tables=()):
    """CP-A comparison. Returns (data_violations, protection_violations)."""
    data, prot = [], []
    counts = {t: c for t, c in s["row_counts"].items() if t not in ignore_tables}
    ref_counts = {t: c for t, c in reference["row_counts"].items() if t not in ignore_tables}
    if set(counts) != set(ref_counts):
        data.append("table set changed: added %s removed %s" % (sorted(set(counts) - set(ref_counts)), sorted(set(ref_counts) - set(counts))))
    for t in sorted(set(counts) & set(ref_counts)):
        if t in FRAMEWORK_TABLES or t in LEDGER_TABLES:
            continue
        if counts[t] != ref_counts[t]:
            data.append("%s rows %d, reference %d" % (t, counts[t], ref_counts[t]))
    for key in ("core_role", "content_types", "permissions", "migrations"):
        if s[key] != reference[key]:
            data.append("%s differs from reference" % key)
    if s["public_register_insert"] != reference["public_register_insert"]:
        prot.append("public_register_insert %s, reference %s" % (s["public_register_insert"], reference["public_register_insert"]))
    for key in ("triggers", "constraints", "functions", "ownership_grants"):
        a, b = set(reference[key]), set(s[key])
        if a != b:
            prot.append("%s: missing %s; unexpected %s" % (key, sorted(a - b)[:5], sorted(b - a)[:5]))
    return data, prot
