# Generated by Django 5.2.15 on 2026-06-09 04:55

# ---------------------------------------------------------
# Governance Header (GP-07)
# ---------------------------------------------------------
# This migration represents a merge point in INTEVIA's
# ontology evolution. Although it contains no operations,
# it forms part of the historical trail showing the moment
# structural ontology (Triad roles) entered the system.
#
# Under GP-07, all ontology-related migrations carry
# governance headers to preserve the evolutionary record.
#
# Ratified by: Carmien
# Date: 2026-06-09
# ---------------------------------------------------------

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_role_alter_profile_display_name_profilerole'),
        ('core', '0003_seed_triad_roles'),
    ]

    operations = [
    ]
