# Generated by Django 5.2.15 on 2026-07-20 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_slice001_contribution_lifecycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=270)),
                ('description', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], db_index=True, default='draft', max_length=24)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_events', to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='EventTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField(max_length=24)),
                ('to_state', models.CharField(max_length=24)),
                ('command', models.CharField(db_index=True, max_length=40)),
                ('authority_reference', models.CharField(max_length=255)),
                ('rationale_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('occurred_at', models.DateTimeField()),
                ('lineage_reference', models.CharField(max_length=255, unique=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_transitions', to='core.profile')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='core.event')),
                ('previous_transition', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_transition', to='core.eventtransition')),
            ],
        ),
        migrations.CreateModel(
            name='EventEvidenceReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255)),
                ('reference_type', models.CharField(db_index=True, max_length=40)),
                ('authority_reference', models.CharField(max_length=255)),
                ('occurred_at', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_references', to='core.event')),
                ('supplied_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplied_event_evidence_references', to='core.profile')),
                ('transition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_references', to='core.eventtransition')),
            ],
        ),
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority_reference', models.CharField(max_length=255)),
                ('attached_at', models.DateTimeField()),
                ('attached_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attached_event_participations', to='core.profile')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations', to='core.event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_participations', to='core.profile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'participant'), name='unique_event_participant')],
            },
        ),
        migrations.AddIndex(
            model_name='eventtransition',
            index=models.Index(fields=['event', 'occurred_at'], name='event_transition_time_idx'),
        ),
        migrations.AddIndex(
            model_name='eventevidencereference',
            index=models.Index(fields=['event', 'occurred_at'], name='event_evidence_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventevidencereference',
            constraint=models.UniqueConstraint(fields=('event', 'reference'), name='unique_event_evidence_reference'),
        ),
    ]
