# Generated by Django 5.2.15 on 2026-07-20 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_event_lifecycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.CharField(max_length=120, unique=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('deprecated', 'Deprecated'), ('archived', 'Archived')], db_index=True, default='draft', max_length=24)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_library_resources', to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='LibraryResourceVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_library_resource_versions', to='core.profile')),
                ('predecessor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor', to='core.libraryresourceversion')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='core.libraryresource')),
            ],
        ),
        migrations.CreateModel(
            name='LibraryResourceTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField(max_length=24)),
                ('to_state', models.CharField(max_length=24)),
                ('command', models.CharField(db_index=True, max_length=48)),
                ('authority_reference', models.CharField(max_length=255)),
                ('rationale_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('occurred_at', models.DateTimeField()),
                ('lineage_reference', models.CharField(max_length=255, unique=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='library_resource_transitions', to='core.profile')),
                ('previous_transition', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_transition', to='core.libraryresourcetransition')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='core.libraryresource')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='core.libraryresourceversion')),
            ],
        ),
        migrations.CreateModel(
            name='LibraryResourceEvidenceReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255)),
                ('reference_type', models.CharField(db_index=True, max_length=40)),
                ('authority_reference', models.CharField(max_length=255)),
                ('occurred_at', models.DateTimeField()),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_references', to='core.libraryresource')),
                ('supplied_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplied_library_evidence_references', to='core.profile')),
                ('transition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_references', to='core.libraryresourcetransition')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_references', to='core.libraryresourceversion')),
            ],
        ),
        migrations.AddField(
            model_name='libraryresource',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_resources', to='core.libraryresourceversion'),
        ),
        migrations.AddConstraint(
            model_name='libraryresourceversion',
            constraint=models.UniqueConstraint(fields=('resource', 'version_number'), name='unique_library_resource_version'),
        ),
        migrations.AddIndex(
            model_name='libraryresourcetransition',
            index=models.Index(fields=['resource', 'occurred_at'], name='library_transition_time_idx'),
        ),
        migrations.AddIndex(
            model_name='libraryresourceevidencereference',
            index=models.Index(fields=['resource', 'occurred_at'], name='library_evidence_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='libraryresourceevidencereference',
            constraint=models.UniqueConstraint(fields=('resource', 'reference'), name='unique_library_evidence_reference'),
        ),
    ]
