# Generated by Django 5.2.15 on 2026-07-20 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_library_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=120, unique=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('retired', 'Retired')], db_index=True, default='draft', max_length=24)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('retired_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_services', to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('capability_purpose', models.CharField(max_length=270)),
                ('domain_intent', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('constraints', models.TextField(blank=True)),
                ('permitted_enactment_mode', models.CharField(choices=[('event', 'Event')], default='event', max_length=24)),
                ('created_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_service_versions', to='core.profile')),
                ('predecessor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor', to='core.serviceversion')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='core.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField(max_length=24)),
                ('to_state', models.CharField(max_length=24)),
                ('command', models.CharField(db_index=True, max_length=48)),
                ('authority_reference', models.CharField(max_length=255)),
                ('occurred_at', models.DateTimeField()),
                ('lineage_reference', models.CharField(max_length=255, unique=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_transitions', to='core.profile')),
                ('previous_transition', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_transition', to='core.servicetransition')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='core.service')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='core.serviceversion')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceEvidenceReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255)),
                ('reference_type', models.CharField(db_index=True, max_length=40)),
                ('authority_reference', models.CharField(max_length=255)),
                ('occurred_at', models.DateTimeField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_references', to='core.service')),
                ('supplied_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplied_service_evidence_references', to='core.profile')),
                ('transition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_references', to='core.servicetransition')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_references', to='core.serviceversion')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceEventAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority_reference', models.CharField(max_length=255)),
                ('evidence_reference', models.CharField(max_length=255)),
                ('occurred_at', models.DateTimeField()),
                ('lineage_reference', models.CharField(max_length=255, unique=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_event_associations', to='core.profile')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_associations', to='core.event')),
                ('service_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_associations', to='core.serviceversion')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_services', to='core.serviceversion'),
        ),
        migrations.CreateModel(
            name='LibraryServiceAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority_reference', models.CharField(max_length=255)),
                ('evidence_reference', models.CharField(max_length=255)),
                ('occurred_at', models.DateTimeField()),
                ('lineage_reference', models.CharField(max_length=255, unique=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='library_service_associations', to='core.profile')),
                ('library_resource_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_associations', to='core.libraryresourceversion')),
                ('service_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='library_associations', to='core.serviceversion')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDeliveryEvidenceReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255)),
                ('authority_reference', models.CharField(max_length=255)),
                ('occurred_at', models.DateTimeField()),
                ('completed_event_transition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_delivery_evidence_references', to='core.eventtransition')),
                ('supplied_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplied_service_delivery_evidence_references', to='core.profile')),
                ('service_event_association', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_evidence_references', to='core.serviceeventassociation')),
            ],
            options={
                'indexes': [models.Index(fields=['service_event_association', 'occurred_at'], name='service_delivery_time_idx')],
                'constraints': [models.UniqueConstraint(fields=('service_event_association', 'reference'), name='unique_service_delivery_evidence')],
            },
        ),
        migrations.AddConstraint(
            model_name='serviceversion',
            constraint=models.UniqueConstraint(fields=('service', 'version_number'), name='unique_service_version'),
        ),
        migrations.AddIndex(
            model_name='servicetransition',
            index=models.Index(fields=['service', 'occurred_at'], name='service_transition_time_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceevidencereference',
            index=models.Index(fields=['service', 'occurred_at'], name='service_evidence_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceevidencereference',
            constraint=models.UniqueConstraint(fields=('service', 'reference'), name='unique_service_evidence_reference'),
        ),
        migrations.AddConstraint(
            model_name='serviceeventassociation',
            constraint=models.UniqueConstraint(fields=('service_version', 'event'), name='unique_service_event_association'),
        ),
        migrations.AddConstraint(
            model_name='libraryserviceassociation',
            constraint=models.UniqueConstraint(fields=('service_version', 'library_resource_version'), name='unique_library_service_association'),
        ),
    ]
