# Generated by Django 5.2.15 on 2026-07-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_service_foundation"),
    ]

    operations = [
        migrations.CreateModel(
            name="CareResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("response_id", models.CharField(max_length=120, unique=True)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("human_request", "Human request"),
                            ("governed_system_event", "Governed system event"),
                        ],
                        max_length=32,
                    ),
                ),
                ("trigger_reference", models.CharField(max_length=255)),
                (
                    "context_source",
                    models.CharField(
                        choices=[
                            ("human_declared", "Human declared"),
                            ("explicit_preference", "Explicit preference"),
                            ("authorised_organism", "Authorised organism"),
                        ],
                        max_length=32,
                    ),
                ),
                ("context_reference", models.CharField(max_length=255)),
                (
                    "output_type",
                    models.CharField(
                        choices=[
                            ("orientation_guidance", "Orientation guidance"),
                            ("clarification_prompt", "Clarification prompt"),
                            ("next_step_suggestion", "Next step suggestion"),
                            ("boundary_signal", "Boundary signal"),
                            ("human_deference", "Human deference"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("content", models.TextField()),
                ("selection_basis", models.CharField(blank=True, max_length=255)),
                (
                    "governing_rule_reference",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "human_response_reference",
                    models.CharField(blank=True, max_length=255),
                ),
                ("authority_reference", models.CharField(max_length=255)),
                ("evidence_reference", models.CharField(max_length=255)),
                ("occurred_at", models.DateTimeField()),
                (
                    "lineage_reference",
                    models.CharField(db_index=True, max_length=255),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="care_responses",
                        to="core.profile",
                    ),
                ),
                (
                    "predecessor",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="successor",
                        to="core.careresponse",
                    ),
                ),
                (
                    "selected_library_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="care_responses",
                        to="core.libraryresourceversion",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["lineage_reference", "occurred_at"],
                        name="care_lineage_time_idx",
                    )
                ],
            },
        ),
    ]
