# Generated by Django 5.2.15 on 2026-07-21 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_care_response_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.CharField(max_length=120, unique=True)),
                ('state', models.CharField(choices=[('registered', 'Registered'), ('cancelled', 'Cancelled')], db_index=True, default='registered', max_length=24)),
                ('origin', models.CharField(choices=[('self', 'Self'), ('third_party', 'Third party')], max_length=24)),
                ('event_state_at_registration', models.CharField(max_length=24)),
                ('eligibility_policy_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('eligibility_basis_type', models.CharField(choices=[('event_policy', 'Event policy'), ('authority_rule', 'Authority rule'), ('event_configuration', 'Event configuration'), ('other', 'Other')], max_length=32)),
                ('eligibility_basis_reference', models.CharField(max_length=255)),
                ('eligibility_evaluated_at', models.DateTimeField()),
                ('registered_at', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='core.event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_registrations', to='core.profile')),
                ('predecessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successors', to='core.eventregistration')),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistrationTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField(max_length=24)),
                ('to_state', models.CharField(max_length=24)),
                ('action_type', models.CharField(choices=[('register_self', 'Register self'), ('register_third_party', 'Register third party'), ('cancel', 'Cancel'), ('re_register', 'Re-register')], db_index=True, max_length=32)),
                ('authority_reference', models.CharField(max_length=255)),
                ('authority_evaluated_at', models.DateTimeField()),
                ('idempotency_key', models.CharField(blank=True, max_length=120, null=True)),
                ('cancellation_basis', models.CharField(blank=True, choices=[('participant_request', 'Participant request'), ('actor_decision', 'Actor decision'), ('event_change', 'Event change'), ('administrative', 'Administrative'), ('other', 'Other')], max_length=32)),
                ('basis_source', models.CharField(blank=True, choices=[('participant_supplied', 'Participant supplied'), ('actor_recorded', 'Actor recorded')], max_length=32)),
                ('occurred_at', models.DateTimeField()),
                ('lineage_reference', models.CharField(max_length=255, unique=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_registration_transitions', to='core.profile')),
                ('authority_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registration_authority_transitions', to='core.event')),
                ('authority_participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registration_authority_subject_transitions', to='core.profile')),
                ('authority_predecessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor_authority_transitions', to='core.eventregistration')),
                ('previous_transition', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_transition', to='core.eventregistrationtransition')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='core.eventregistration')),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistrationEvidenceReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255)),
                ('reference_type', models.CharField(db_index=True, max_length=40)),
                ('occurred_at', models.DateTimeField()),
                ('supplied_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplied_event_registration_evidence', to='core.profile')),
                ('transition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_references', to='core.eventregistrationtransition')),
            ],
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['event', 'participant', 'state'], name='event_reg_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'registered')), fields=('event', 'participant'), name='one_active_event_registration'),
        ),
        migrations.AddConstraint(
            model_name='eventregistration',
            constraint=models.CheckConstraint(condition=models.Q(('predecessor__isnull', True), models.Q(('pk', models.F('predecessor_id')), _negated=True), _connector='OR'), name='event_registration_not_self_predecessor'),
        ),
        migrations.AddConstraint(
            model_name='eventregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('predecessor__isnull', False)), fields=('predecessor',), name='one_event_registration_successor'),
        ),
        migrations.AddIndex(
            model_name='eventregistrationtransition',
            index=models.Index(fields=['registration', 'occurred_at'], name='event_reg_transition_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventregistrationtransition',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('actor', 'action_type', 'idempotency_key'), name='unique_event_reg_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='eventregistrationevidencereference',
            constraint=models.UniqueConstraint(fields=('transition', 'reference'), name='unique_event_registration_evidence'),
        ),
    ]
