# Generated by Django 5.2.15 on 2026-07-22 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_s007_identity_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_id', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('voided', 'Voided')], db_index=True, default='present', max_length=16)),
                ('observed_at', models.DateTimeField()),
                ('origin', models.CharField(choices=[('registered', 'Registered'), ('governed_walk_in', 'Governed walk-in')], max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='core.event')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_attendance_records', to='core.identity')),
                ('supporting_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supported_attendance_records', to='core.eventregistration')),
            ],
        ),
        migrations.CreateModel(
            name='EventAttendanceTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('record', 'Record'), ('correct', 'Correct'), ('void', 'Void'), ('reinstate', 'Reinstate')], db_index=True, max_length=16)),
                ('from_status', models.CharField(max_length=16)),
                ('to_status', models.CharField(max_length=16)),
                ('authority_reference', models.CharField(max_length=255)),
                ('authority_evaluated_at', models.DateTimeField()),
                ('origin', models.CharField(choices=[('registered', 'Registered'), ('governed_walk_in', 'Governed walk-in')], max_length=24)),
                ('previous_observed_at', models.DateTimeField(blank=True, null=True)),
                ('resulting_observed_at', models.DateTimeField()),
                ('basis', models.CharField(blank=True, max_length=255)),
                ('rationale', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('payload_fingerprint', models.CharField(max_length=64)),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_attendance_transitions', to='core.identity')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='core.eventattendance')),
                ('previous_supporting_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_transitions_from_registration', to='core.eventregistration')),
                ('previous_transition', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_transition', to='core.eventattendancetransition')),
                ('resulting_supporting_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_transitions_to_registration', to='core.eventregistration')),
            ],
        ),
        migrations.CreateModel(
            name='EventAttendanceEvidenceReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(max_length=40)),
                ('classification', models.CharField(choices=[('actor_attestation', 'Actor attestation')], db_index=True, max_length=32)),
                ('reference', models.CharField(max_length=255)),
                ('provenance', models.CharField(max_length=255)),
                ('supplied_at', models.DateTimeField()),
                ('supplied_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplied_event_attendance_evidence', to='core.identity')),
                ('transition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_references', to='core.eventattendancetransition')),
            ],
        ),
        migrations.CreateModel(
            name='EventAttendanceEligibilityReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basis_type', models.CharField(choices=[('governed_walk_in', 'Governed walk-in')], max_length=32)),
                ('basis_reference', models.CharField(max_length=255)),
                ('authority_reference', models.CharField(max_length=255)),
                ('event_state_snapshot', models.CharField(max_length=24)),
                ('evaluated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_event_attendance_eligibility_receipts', to='core.identity')),
                ('attendance', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='walk_in_eligibility_receipt', to='core.eventattendance')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_eligibility_receipts', to='core.event')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_attendance_eligibility_receipts', to='core.identity')),
                ('record_transition', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='walk_in_eligibility_receipt', to='core.eventattendancetransition')),
            ],
        ),
        migrations.AddIndex(
            model_name='eventattendance',
            index=models.Index(fields=['event', 'subject', 'status'], name='event_attendance_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventattendance',
            constraint=models.UniqueConstraint(fields=('event', 'subject'), name='unique_event_subject_attendance'),
        ),
        migrations.AddIndex(
            model_name='eventattendancetransition',
            index=models.Index(fields=['attendance', 'recorded_at'], name='attendance_transition_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventattendancetransition',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gte', 1)), name='attendance_sequence_positive'),
        ),
        migrations.AddConstraint(
            model_name='eventattendancetransition',
            constraint=models.CheckConstraint(condition=models.Q(('previous_transition__isnull', True), models.Q(('pk', models.F('previous_transition_id')), _negated=True), _connector='OR'), name='attendance_transition_not_self_previous'),
        ),
        migrations.AddConstraint(
            model_name='eventattendancetransition',
            constraint=models.UniqueConstraint(condition=models.Q(('previous_transition__isnull', True)), fields=('attendance',), name='one_initial_attendance_transition'),
        ),
        migrations.AddConstraint(
            model_name='eventattendancetransition',
            constraint=models.UniqueConstraint(fields=('attendance', 'sequence'), name='unique_attendance_sequence'),
        ),
        migrations.AddConstraint(
            model_name='eventattendancetransition',
            constraint=models.UniqueConstraint(condition=models.Q(('previous_transition__isnull', False)), fields=('previous_transition',), name='one_attendance_transition_successor'),
        ),
        migrations.AddConstraint(
            model_name='eventattendancetransition',
            constraint=models.UniqueConstraint(fields=('actor', 'action', 'idempotency_key'), name='unique_attendance_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='eventattendanceevidencereference',
            constraint=models.UniqueConstraint(fields=('transition', 'reference'), name='unique_attendance_evidence_reference'),
        ),
    ]
