# Generated by Django 5.2.15 on 2026-07-27 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_s011b_event_resource_relationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.UUIDField(editable=False)),
                ('initiating_domain', models.CharField(choices=[('core', 'Core'), ('organism', 'Organism'), ('library', 'Library'), ('education', 'Education'), ('event', 'Event'), ('service', 'Service'), ('discussion', 'Discussion'), ('engagement', 'Engagement'), ('exchange', 'Exchange')], max_length=16)),
                ('initiating_domain_reference', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('unassigned', 'Unassigned'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('completed', 'Completed'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], max_length=16)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='created_service_activities', to='core.identity')),
                ('service_version', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='service_activities', to='core.serviceversion')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceActivityTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('ASSIGN', 'Assign'), ('ACCEPT_ASSIGNMENT', 'Accept assignment'), ('DECLINE_ASSIGNMENT', 'Decline assignment'), ('SUBMIT_WORK', 'Submit work'), ('REVIEW_WORK', 'Review work'), ('COMPLETE_ACTIVITY', 'Complete activity'), ('CANCEL_ACTIVITY', 'Cancel activity')], max_length=32)),
                ('from_state', models.CharField(blank=True, choices=[('unassigned', 'Unassigned'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('completed', 'Completed'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], max_length=16, null=True)),
                ('to_state', models.CharField(choices=[('unassigned', 'Unassigned'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('completed', 'Completed'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], max_length=16)),
                ('actor_access_epoch', models.PositiveBigIntegerField()),
                ('authority_reference', models.CharField(max_length=255)),
                ('authority_decision_reference', models.CharField(max_length=71)),
                ('authority_evaluated_at', models.DateTimeField()),
                ('request_reference', models.CharField(max_length=128)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('payload_fingerprint', models.CharField(max_length=64)),
                ('occurred_at', models.DateTimeField()),
                ('lineage_reference', models.CharField(max_length=71)),
                ('activity', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='core.serviceactivity')),
                ('actor', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='service_activity_transitions', to='core.identity')),
                ('previous_transition', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_transition_rows', to='core.serviceactivitytransition')),
            ],
        ),
        migrations.AddField(
            model_name='serviceactivity',
            name='head_transition',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='headed_activity', to='core.serviceactivitytransition'),
        ),
        migrations.CreateModel(
            name='ServiceActivityAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_reference', models.CharField(max_length=255)),
                ('assigned_at', models.DateTimeField()),
                ('activity', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='assignment_rows', to='core.serviceactivity')),
                ('assigned_by', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='service_activity_assignments_made', to='core.identity')),
                ('assignee', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='service_activity_assignments', to='core.identity')),
                ('transition', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='assignment_occurrences', to='core.serviceactivitytransition')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceWorkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_reference', models.CharField(max_length=255)),
                ('submitted_at', models.DateTimeField()),
                ('activity', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='work_submission_rows', to='core.serviceactivity')),
                ('submitted_by', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='service_work_submissions', to='core.identity')),
                ('transition', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='work_submission_occurrences', to='core.serviceactivitytransition')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceActivityReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_reference', models.CharField(max_length=255)),
                ('reviewed_at', models.DateTimeField()),
                ('reviewed_by', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='service_activity_reviews', to='core.identity')),
                ('transition', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='review_occurrences', to='core.serviceactivitytransition')),
                ('submission', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='activity_review_rows', to='core.serviceworksubmission')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceActivityEvidenceReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_kind', models.CharField(choices=[('activity_basis', 'Activity basis'), ('assignment_basis', 'Assignment basis'), ('submission_support', 'Submission support'), ('review_record', 'Review record'), ('completion_record', 'Completion record'), ('cancellation_basis', 'Cancellation basis'), ('decline_basis', 'Decline basis')], max_length=32)),
                ('reference', models.CharField(max_length=255)),
                ('authority_reference', models.CharField(max_length=255)),
                ('occurred_at', models.DateTimeField()),
                ('supplied_by', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='service_activity_evidence', to='core.identity')),
                ('transition', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='evidence_references', to='core.serviceactivitytransition')),
            ],
        ),
        migrations.AddIndex(
            model_name='serviceactivitytransition',
            index=models.Index(fields=['actor'], name='s012_transition_actor_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceactivitytransition',
            index=models.Index(fields=['activity', 'action'], name='s012_transition_activity_action_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceactivitytransition',
            constraint=models.UniqueConstraint(fields=('activity', 'sequence'), name='s012_transition_activity_sequence_uniq'),
        ),
        migrations.AddConstraint(
            model_name='serviceactivitytransition',
            constraint=models.UniqueConstraint(fields=('actor', 'action', 'idempotency_key'), name='s012_activity_actor_action_idem_uniq'),
        ),
        migrations.AddConstraint(
            model_name='serviceactivitytransition',
            constraint=models.UniqueConstraint(condition=models.Q(('previous_transition__isnull', True)), fields=('activity',), name='s012_transition_initial_uniq'),
        ),
        migrations.AddConstraint(
            model_name='serviceactivitytransition',
            constraint=models.UniqueConstraint(condition=models.Q(('previous_transition__isnull', False)), fields=('previous_transition',), name='s012_transition_successor_uniq'),
        ),
        migrations.AddConstraint(
            model_name='serviceactivitytransition',
            constraint=models.UniqueConstraint(fields=('lineage_reference',), name='s012_transition_lineage_ref_uniq'),
        ),
        migrations.AddConstraint(
            model_name='serviceactivitytransition',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gte', 1)), name='s012_transition_sequence_positive_ck'),
        ),
        migrations.AddConstraint(
            model_name='serviceactivitytransition',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ('CREATE', 'ASSIGN', 'ACCEPT_ASSIGNMENT', 'DECLINE_ASSIGNMENT', 'SUBMIT_WORK', 'REVIEW_WORK', 'COMPLETE_ACTIVITY', 'CANCEL_ACTIVITY'))), name='s012_transition_action_valid_ck'),
        ),
        migrations.AddConstraint(
            model_name='serviceactivitytransition',
            constraint=models.CheckConstraint(condition=models.Q(('from_state__isnull', True), ('from_state__in', ('unassigned', 'assigned', 'in_progress', 'submitted', 'reviewed', 'completed', 'declined', 'cancelled')), _connector='OR'), name='s012_transition_from_state_valid_ck'),
        ),
        migrations.AddConstraint(
            model_name='serviceactivitytransition',
            constraint=models.CheckConstraint(condition=models.Q(('to_state__in', ('unassigned', 'assigned', 'in_progress', 'submitted', 'reviewed', 'completed', 'declined', 'cancelled'))), name='s012_transition_to_state_valid_ck'),
        ),
        migrations.AddConstraint(
            model_name='serviceactivitytransition',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('action', 'CREATE'), ('from_state__isnull', True), ('to_state', 'unassigned')), models.Q(('action', 'ASSIGN'), ('from_state', 'unassigned'), ('to_state', 'assigned')), models.Q(('action', 'ACCEPT_ASSIGNMENT'), ('from_state', 'assigned'), ('to_state', 'in_progress')), models.Q(('action', 'DECLINE_ASSIGNMENT'), ('from_state', 'assigned'), ('to_state', 'declined')), models.Q(('action', 'SUBMIT_WORK'), ('from_state', 'in_progress'), ('to_state', 'submitted')), models.Q(('action', 'REVIEW_WORK'), ('from_state', 'submitted'), ('to_state', 'reviewed')), models.Q(('action', 'COMPLETE_ACTIVITY'), ('from_state', 'reviewed'), ('to_state', 'completed')), models.Q(('action', 'CANCEL_ACTIVITY'), ('from_state__in', ('unassigned', 'assigned', 'in_progress', 'submitted', 'reviewed')), ('to_state', 'cancelled')), _connector='OR'), name='s012_transition_edge_valid_ck'),
        ),
        migrations.AddConstraint(
            model_name='serviceactivitytransition',
            constraint=models.CheckConstraint(condition=models.Q(('payload_fingerprint__regex', '^[0-9a-f]{64}$')), name='s012_transition_payload_hex_ck'),
        ),
        migrations.AddConstraint(
            model_name='serviceactivitytransition',
            constraint=models.CheckConstraint(condition=models.Q(('authority_decision_reference__regex', '^s012d1:[0-9a-f]{64}$')), name='s012_transition_decision_ref_ck'),
        ),
        migrations.AddConstraint(
            model_name='serviceactivitytransition',
            constraint=models.CheckConstraint(condition=models.Q(('lineage_reference__regex', '^s012l1:[0-9a-f]{64}$')), name='s012_transition_lineage_ref_ck'),
        ),
        migrations.AddConstraint(
            model_name='serviceactivitytransition',
            constraint=models.CheckConstraint(condition=models.Q(('authority_reference__regex', '.*\\S.*'), ('request_reference__regex', '.*\\S.*'), ('idempotency_key__regex', '.*\\S.*')), name='s012_transition_refs_nonempty_ck'),
        ),
        migrations.AddIndex(
            model_name='serviceactivityevidencereference',
            index=models.Index(fields=['supplied_by'], name='s012_evidence_supplied_by_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceactivityevidencereference',
            constraint=models.UniqueConstraint(fields=('transition', 'evidence_kind', 'reference'), name='s012_evidence_tuple_uniq'),
        ),
        migrations.AddConstraint(
            model_name='serviceactivityevidencereference',
            constraint=models.CheckConstraint(condition=models.Q(('evidence_kind__in', ('activity_basis', 'assignment_basis', 'submission_support', 'review_record', 'completion_record', 'cancellation_basis', 'decline_basis'))), name='s012_evidence_kind_valid_ck'),
        ),
        migrations.AddConstraint(
            model_name='serviceactivityevidencereference',
            constraint=models.CheckConstraint(condition=models.Q(('reference__regex', '.*\\S.*'), ('authority_reference__regex', '.*\\S.*')), name='s012_evidence_refs_nonempty_ck'),
        ),
        migrations.AddIndex(
            model_name='serviceactivityassignment',
            index=models.Index(fields=['assignee'], name='s012_assignment_assignee_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceactivityassignment',
            index=models.Index(fields=['assigned_by'], name='s012_assignment_assigned_by_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceactivityassignment',
            constraint=models.UniqueConstraint(fields=('activity',), name='s012_assignment_activity_uniq'),
        ),
        migrations.AddConstraint(
            model_name='serviceactivityassignment',
            constraint=models.UniqueConstraint(fields=('transition',), name='s012_assignment_transition_uniq'),
        ),
        migrations.AddConstraint(
            model_name='serviceactivityassignment',
            constraint=models.CheckConstraint(condition=models.Q(('assignment_reference__regex', '.*\\S.*')), name='s012_assignment_refs_nonempty_ck'),
        ),
        migrations.AddIndex(
            model_name='serviceactivity',
            index=models.Index(fields=['service_version'], name='s012_activity_service_version_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceactivity',
            index=models.Index(fields=['state'], name='s012_activity_state_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceactivity',
            index=models.Index(fields=['created_by'], name='s012_activity_created_by_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceactivity',
            constraint=models.UniqueConstraint(fields=('activity_id',), name='s012_activity_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='serviceactivity',
            constraint=models.UniqueConstraint(condition=models.Q(('head_transition__isnull', False)), fields=('head_transition',), name='s012_activity_head_uniq'),
        ),
        migrations.AddConstraint(
            model_name='serviceactivity',
            constraint=models.CheckConstraint(condition=models.Q(('initiating_domain__in', ('core', 'organism', 'library', 'education', 'event', 'service', 'discussion', 'engagement', 'exchange'))), name='s012_activity_domain_valid_ck'),
        ),
        migrations.AddConstraint(
            model_name='serviceactivity',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ('unassigned', 'assigned', 'in_progress', 'submitted', 'reviewed', 'completed', 'declined', 'cancelled'))), name='s012_activity_state_valid_ck'),
        ),
        migrations.AddConstraint(
            model_name='serviceactivity',
            constraint=models.CheckConstraint(condition=models.Q(('initiating_domain_reference__regex', '.*\\S.*')), name='s012_activity_refs_nonempty_ck'),
        ),
        migrations.AddIndex(
            model_name='serviceworksubmission',
            index=models.Index(fields=['submitted_by'], name='s012_submission_submitted_by_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceworksubmission',
            constraint=models.UniqueConstraint(fields=('activity',), name='s012_submission_activity_uniq'),
        ),
        migrations.AddConstraint(
            model_name='serviceworksubmission',
            constraint=models.UniqueConstraint(fields=('transition',), name='s012_submission_transition_uniq'),
        ),
        migrations.AddConstraint(
            model_name='serviceworksubmission',
            constraint=models.CheckConstraint(condition=models.Q(('submission_reference__regex', '.*\\S.*')), name='s012_submission_refs_nonempty_ck'),
        ),
        migrations.AddIndex(
            model_name='serviceactivityreview',
            index=models.Index(fields=['reviewed_by'], name='s012_review_reviewed_by_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceactivityreview',
            constraint=models.UniqueConstraint(fields=('submission',), name='s012_review_submission_uniq'),
        ),
        migrations.AddConstraint(
            model_name='serviceactivityreview',
            constraint=models.UniqueConstraint(fields=('transition',), name='s012_review_transition_uniq'),
        ),
        migrations.AddConstraint(
            model_name='serviceactivityreview',
            constraint=models.CheckConstraint(condition=models.Q(('review_reference__regex', '.*\\S.*')), name='s012_review_refs_nonempty_ck'),
        ),
    ]
