# Generated by Django 5.2.15 on 2026-08-06 22:42

import core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


GENESIS_NAMESPACE = "INTEVIA_RESERVED_GENESIS_AUTHORITY_V1"
GENESIS_SOURCE = (
    "urn:intevia:governed-source:reserved-genesis:"
    "human-governor:carmian-owen:intevia-v1.0"
)
GENESIS_INVOCATION_SHA256 = (
    "57a247b376dfff11834ba8521ed66589a02b2cbf3c45e04bfc6f3738ea7367d7"
)

IMMUTABLE_ANCHORS = {
    "core_authorityprincipal": (
        "principal_uuid",
        "canonical_governed_source_id",
        "governed_source_namespace",
    ),
    "core_authoritybasis": (
        "basis_uuid",
        "authority_principal_id",
        "derivation_root_principal_id",
        "issuer_id",
        "authority_class",
        "scope_fingerprint",
        "instrument_reference",
        "evidence_reference",
        "issued_at",
        "effective_at",
        "received_at",
        "recorded_at",
        "superseded_basis_id",
    ),
    "core_emergencyauthorityenvelope": (
        "envelope_uuid",
        "beneficiary_id",
        "authority_principal_id",
        "derivation_root_principal_id",
        "qualifying_constitutional_grant_id",
        "permitted_command_set",
        "target_scope_set",
        "proportionality_bounds",
        "hard_expiry",
    ),
    "core_governedvisibilitygrant": (
        "grant_uuid",
        "subject_type",
        "subject_id",
        "audience_type",
        "audience_id",
        "capacity_binding",
        "fields_permitted",
        "purpose_reference",
        "granting_authority_id",
        "expiry",
        "lineage_reference",
    ),
    "core_livingorganism": (
        "organism_id",
        "slug",
        "constitutional_spine_reference",
        "founding_insert_xid",
        "founding_authority_basis_id",
        "founder_identity_id",
    ),
    "core_circle": ("circle_uuid", "parent_organism_id"),
    "core_organismmembership": (
        "membership_uuid",
        "identity_id",
        "living_organism_id",
    ),
    "core_contextualroleassignment": (
        "assignment_uuid",
        "membership_id",
        "role_definition_id",
        "circle_id",
    ),
}

APPEND_ONLY_TABLES = (
    "core_authorityprincipalaliasreview",
    "core_authorityderivationedge",
    "core_governeddetermination",
    "core_organismcommandreceipt",
)


def install_s015_postgresql_guardians(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        """
        CREATE OR REPLACE FUNCTION s015_refuse_row_mutation()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'S015 immutable or append-only row mutation refused'
                USING ERRCODE = 'integrity_constraint_violation';
        END;
        $$;

        CREATE OR REPLACE FUNCTION s015_guard_genesis_principal()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF NEW.governed_source_namespace = 'INTEVIA_RESERVED_GENESIS_AUTHORITY_V1'
               AND (NEW.canonical_governed_source_id <> 'urn:intevia:governed-source:reserved-genesis:human-governor:carmian-owen:intevia-v1.0'
                    OR NEW.bootstrap_invocation_fingerprint <> '57a247b376dfff11834ba8521ed66589a02b2cbf3c45e04bfc6f3738ea7367d7')
            THEN
                RAISE EXCEPTION 'S015 genesis identity does not match the Human invocation'
                    USING ERRCODE = 'integrity_constraint_violation';
            END IF;
            RETURN NEW;
        END;
        $$;

        CREATE OR REPLACE FUNCTION s015_guard_derivation_edge()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF NEW.principal_id = NEW.root_principal_id OR EXISTS (
                WITH RECURSIVE ancestry(principal_id, root_principal_id) AS (
                    SELECT principal_id, root_principal_id
                    FROM core_authorityderivationedge
                    WHERE principal_id = NEW.root_principal_id
                    UNION ALL
                    SELECT edge.principal_id, edge.root_principal_id
                    FROM core_authorityderivationedge edge
                    JOIN ancestry prior ON edge.principal_id = prior.root_principal_id
                )
                SELECT 1 FROM ancestry WHERE root_principal_id = NEW.principal_id
            ) THEN
                RAISE EXCEPTION 'S015 authority derivation cycle refused'
                    USING ERRCODE = 'integrity_constraint_violation';
            END IF;
            RETURN NEW;
        END;
        $$;

        CREATE OR REPLACE FUNCTION s015_prepare_living_organism_insert()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF NEW.founding_insert_xid IS NOT NULL
               OR NEW.founding_authority_basis_id IS NOT NULL
               OR NEW.founder_identity_id IS NOT NULL
               OR NEW.state <> 'FOUNDING_PENDING'
            THEN
                RAISE EXCEPTION 'S015 founding root must begin as an empty pending root'
                    USING ERRCODE = 'integrity_constraint_violation';
            END IF;
            NEW.founding_insert_xid := pg_current_xact_id();
            RETURN NEW;
        END;
        $$;

        CREATE OR REPLACE FUNCTION s015_guard_founding_completion_update()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF OLD.founding_authority_basis_id IS NULL
               AND OLD.founder_identity_id IS NULL
               AND NEW.founding_authority_basis_id IS NOT NULL
               AND NEW.founder_identity_id IS NOT NULL
               AND OLD.founding_insert_xid = pg_current_xact_id()
               AND NEW.founding_insert_xid = OLD.founding_insert_xid
               AND EXISTS (
                   SELECT 1 FROM core_organismmembership membership
                   WHERE membership.living_organism_id = OLD.id
                     AND membership.identity_id = NEW.founder_identity_id
                     AND membership.state IN ('ACTIVE', 'PROBATIONARY')
               )
               AND EXISTS (
                   SELECT 1
                   FROM core_contextualroleassignment assignment
                   JOIN core_organismmembership membership
                     ON membership.id = assignment.membership_id
                   JOIN core_organismroledefinition role
                     ON role.id = assignment.role_definition_id
                   WHERE membership.living_organism_id = OLD.id
                     AND membership.identity_id = NEW.founder_identity_id
                     AND role.code = 'FOUNDER_STEWARD'
                     AND assignment.state = 'ACTIVE'
               )
            THEN
                RETURN NEW;
            END IF;
            RAISE EXCEPTION 'S015 founding completion update refused'
                USING ERRCODE = 'integrity_constraint_violation';
        END;
        $$;

        CREATE OR REPLACE FUNCTION s015_validate_completed_founding()
        RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE
            completed boolean;
        BEGIN
            SELECT founding_authority_basis_id IS NOT NULL
                   AND founder_identity_id IS NOT NULL
                   AND state <> 'FOUNDING_PENDING'
            INTO completed
            FROM core_livingorganism
            WHERE id = NEW.id;
            IF completed IS DISTINCT FROM TRUE THEN
                RAISE EXCEPTION 'S015 incomplete founding cannot commit'
                    USING ERRCODE = 'integrity_constraint_violation';
            END IF;
            RETURN NULL;
        END;
        $$;
        """
    )
    for table, columns in IMMUTABLE_ANCHORS.items():
        if table == "core_livingorganism":
            ordinary_columns = columns[:4]
            for column in ordinary_columns:
                schema_editor.execute(
                    f"CREATE TRIGGER s015_{table[5:]}_{column}_immutable "
                    f"BEFORE UPDATE OF {column} ON {table} FOR EACH ROW "
                    "EXECUTE FUNCTION s015_refuse_row_mutation()"
                )
            for column in columns[4:]:
                schema_editor.execute(
                    f"CREATE TRIGGER s015_{table[5:]}_{column}_complete "
                    f"BEFORE UPDATE OF {column} ON {table} FOR EACH ROW "
                    "EXECUTE FUNCTION s015_guard_founding_completion_update()"
                )
        else:
            for column in columns:
                schema_editor.execute(
                    f"CREATE TRIGGER s015_{table[5:]}_{column}_immutable "
                    f"BEFORE UPDATE OF {column} ON {table} FOR EACH ROW "
                    "EXECUTE FUNCTION s015_refuse_row_mutation()"
                )
        schema_editor.execute(
            f"CREATE TRIGGER s015_{table[5:]}_delete_immutable "
            f"BEFORE DELETE ON {table} FOR EACH ROW "
            "EXECUTE FUNCTION s015_refuse_row_mutation()"
        )
        schema_editor.execute(
            f"CREATE TRIGGER s015_{table[5:]}_truncate_immutable "
            f"BEFORE TRUNCATE ON {table} FOR EACH STATEMENT "
            "EXECUTE FUNCTION s015_refuse_row_mutation()"
        )
    for table in APPEND_ONLY_TABLES:
        for operation in ("UPDATE", "DELETE"):
            schema_editor.execute(
                f"CREATE TRIGGER s015_{table[5:]}_{operation.lower()}_append_only "
                f"BEFORE {operation} ON {table} FOR EACH ROW "
                "EXECUTE FUNCTION s015_refuse_row_mutation()"
            )
        schema_editor.execute(
            f"CREATE TRIGGER s015_{table[5:]}_truncate_append_only "
            f"BEFORE TRUNCATE ON {table} FOR EACH STATEMENT "
            "EXECUTE FUNCTION s015_refuse_row_mutation()"
        )
    schema_editor.execute(
        """
        CREATE TRIGGER s015_genesis_principal_insert
        BEFORE INSERT ON core_authorityprincipal FOR EACH ROW
        EXECUTE FUNCTION s015_guard_genesis_principal();

        CREATE TRIGGER s015_derivation_edge_insert
        BEFORE INSERT ON core_authorityderivationedge FOR EACH ROW
        EXECUTE FUNCTION s015_guard_derivation_edge();

        CREATE TRIGGER s015_living_organism_prepare_insert
        BEFORE INSERT ON core_livingorganism FOR EACH ROW
        EXECUTE FUNCTION s015_prepare_living_organism_insert();

        CREATE CONSTRAINT TRIGGER s015_living_organism_founding_complete
        AFTER INSERT OR UPDATE ON core_livingorganism
        DEFERRABLE INITIALLY DEFERRED FOR EACH ROW
        EXECUTE FUNCTION s015_validate_completed_founding();
        """
    )


def remove_s015_postgresql_guardians(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        """
        DROP FUNCTION IF EXISTS s015_validate_completed_founding() CASCADE;
        DROP FUNCTION IF EXISTS s015_guard_founding_completion_update() CASCADE;
        DROP FUNCTION IF EXISTS s015_prepare_living_organism_insert() CASCADE;
        DROP FUNCTION IF EXISTS s015_guard_derivation_edge() CASCADE;
        DROP FUNCTION IF EXISTS s015_guard_genesis_principal() CASCADE;
        DROP FUNCTION IF EXISTS s015_refuse_row_mutation() CASCADE;
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_s014_education_course_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('canonical_governed_source_id', models.CharField(max_length=255, unique=True)),
                ('governed_source_namespace', models.CharField(max_length=90)),
                ('display_label', models.CharField(max_length=120)),
                ('bootstrap_invocation_fingerprint', models.CharField(blank=True, max_length=64, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('governed_source_namespace', 'INTEVIA_RESERVED_GENESIS_AUTHORITY_V1')), fields=('governed_source_namespace',), name='s015_reserved_genesis_namespace_uniq'), models.CheckConstraint(condition=models.Q(('canonical_governed_source_id__regex', '.*\\S.*')), name='s015_principal_source_nonempty_ck')],
            },
        ),
        migrations.CreateModel(
            name='AuthorityBasis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basis_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('authority_class', models.CharField(max_length=64)),
                ('scope_fingerprint', models.CharField(max_length=64)),
                ('instrument_reference', models.CharField(max_length=255)),
                ('evidence_reference', models.CharField(max_length=255)),
                ('issued_at', models.DateTimeField()),
                ('effective_at', models.DateTimeField()),
                ('received_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_authority_bases', to='core.identity')),
                ('superseded_basis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseding_bases', to='core.authoritybasis')),
                ('authority_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authority_bases', to='core.authorityprincipal')),
                ('derivation_root_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooted_authority_bases', to='core.authorityprincipal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuthorityPrincipalAliasReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('candidate_governed_source_id', models.CharField(max_length=255)),
                ('candidate_namespace', models.CharField(max_length=90)),
                ('state', models.CharField(choices=[('AUTHORITY_EQUIVALENCE_UNKNOWN', 'Authority equivalence unknown'), ('BOUND_TO_EXISTING_PRINCIPAL', 'Bound to existing principal'), ('DISTINCT_CANONICAL_IDENTITY', 'Distinct canonical identity')], max_length=40)),
                ('authority_reference', models.CharField(max_length=255)),
                ('evidence_reference', models.CharField(max_length=255)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('possible_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alias_reviews', to='core.authorityprincipal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GovernedDetermination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('determination_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('determination_type', models.CharField(choices=[('LEGAL_BASIS_QUALIFICATION', 'Legal Basis Qualification'), ('CONSTITUTIONAL_AUTHORITY_QUALIFICATION', 'Constitutional Authority Qualification'), ('EXECUTION_ELIGIBILITY_QUALIFICATION', 'Execution Eligibility Qualification'), ('PROPAGATION_VERIFICATION_REFERENCE', 'Propagation Verification Reference'), ('INDEPENDENCE_DETERMINATION', 'Independence Determination'), ('UNAVAILABILITY_DETERMINATION', 'Unavailability Determination'), ('DEPENDENCY_CLOSURE_DETERMINATION', 'Dependency Closure Determination'), ('CONSEQUENTIAL_ACTION_CLASSIFICATION', 'Consequential Action Classification'), ('QUALIFICATION_REASSESSMENT', 'Qualification Reassessment')], max_length=52)),
                ('result', models.CharField(max_length=40)),
                ('evidence_reference', models.CharField(max_length=255)),
                ('method_reference', models.CharField(max_length=255)),
                ('scope_fingerprint', models.CharField(max_length=64)),
                ('independence_state', models.CharField(max_length=32)),
                ('occurred_at', models.DateTimeField()),
                ('effective_at', models.DateTimeField()),
                ('received_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('determiner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='made_governed_determinations', to='core.identity')),
                ('model_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authored_governed_determinations', to='core.identity')),
                ('relied_upon_authority_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relied_upon_determinations', to='core.authorityprincipal')),
                ('safeguard_beneficiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='beneficiary_governed_determinations', to='core.identity')),
                ('tested_actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tested_governed_determinations', to='core.identity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmergencyAuthorityEnvelope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envelope_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('permitted_command_set', models.JSONField()),
                ('target_scope_set', models.JSONField()),
                ('proportionality_bounds', models.JSONField()),
                ('hard_expiry', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('authority_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emergency_authority_envelopes', to='core.authorityprincipal')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emergency_authority_envelopes', to='core.identity')),
                ('derivation_root_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooted_emergency_authority_envelopes', to='core.authorityprincipal')),
                ('qualifying_constitutional_grant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qualified_emergency_authority_envelopes', to='core.governeddetermination')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GovernedVisibilityGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('subject_type', models.CharField(max_length=48)),
                ('subject_id', models.UUIDField()),
                ('audience_type', models.CharField(max_length=48)),
                ('audience_id', models.UUIDField()),
                ('capacity_binding', models.CharField(max_length=255)),
                ('fields_permitted', models.JSONField()),
                ('purpose_reference', models.CharField(max_length=255)),
                ('expiry', models.DateTimeField()),
                ('lineage_reference', models.CharField(max_length=71, unique=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('granting_authority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visibility_grants', to='core.authoritybasis')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LivingOrganism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organism_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(max_length=90, unique=True)),
                ('state', models.CharField(choices=[('FOUNDING_PENDING', 'Founding Pending'), ('ACTIVE', 'Active'), ('RESTRICTED_CONTINUITY', 'Restricted Continuity'), ('DORMANT', 'Dormant'), ('CLOSED', 'Closed')], default='FOUNDING_PENDING', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_state_effective_at', models.DateTimeField()),
                ('state_known_at', models.DateTimeField()),
                ('state_source_event_set_fingerprint', models.CharField(max_length=64)),
                ('constitutional_spine_reference', models.CharField(max_length=255)),
                ('founding_insert_xid', core.models.FoundingTransactionIdField(editable=False, null=True)),
                ('founder_identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='founded_living_organisms', to='core.identity')),
                ('founding_authority_basis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='founded_living_organisms', to='core.authoritybasis')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circle_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('state', models.CharField(choices=[('DORMANT', 'Dormant'), ('ELIGIBLE', 'Eligible'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CLOSED', 'Closed')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_state_effective_at', models.DateTimeField()),
                ('state_known_at', models.DateTimeField()),
                ('state_source_event_set_fingerprint', models.CharField(max_length=64)),
                ('founding_reference', models.CharField(max_length=255)),
                ('parent_organism', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='circles', to='core.livingorganism')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganismMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('state', models.CharField(choices=[('PROPOSED', 'Proposed'), ('ACTIVE', 'Active'), ('PROBATIONARY', 'Probationary'), ('SUSPENDED', 'Suspended'), ('ENDED', 'Ended')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_state_effective_at', models.DateTimeField()),
                ('state_known_at', models.DateTimeField()),
                ('state_source_event_set_fingerprint', models.CharField(max_length=64)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organism_memberships', to='core.identity')),
                ('living_organism', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='core.livingorganism')),
            ],
        ),
        migrations.CreateModel(
            name='OrganismRoleDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=48)),
                ('scope', models.CharField(choices=[('LIVING_ORGANISM', 'Living Organism'), ('CIRCLE', 'Circle')], max_length=20)),
                ('definition_version', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('living_organism', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_definitions', to='core.livingorganism')),
            ],
        ),
        migrations.CreateModel(
            name='ContextualRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('state', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_state_effective_at', models.DateTimeField()),
                ('state_known_at', models.DateTimeField()),
                ('state_source_event_set_fingerprint', models.CharField(max_length=64)),
                ('circle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='role_assignments', to='core.circle')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contextual_role_assignments', to='core.organismmembership')),
                ('role_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='core.organismroledefinition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuthorityDerivationEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('authority_reference', models.CharField(max_length=255)),
                ('evidence_reference', models.CharField(max_length=255)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derivation_edges', to='core.authorityprincipal')),
                ('root_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='root_derivation_edges', to='core.authorityprincipal')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('principal', 'root_principal'), name='s015_principal_root_edge_uniq'), models.CheckConstraint(condition=models.Q(('principal', models.F('root_principal')), _negated=True), name='s015_derivation_not_self_ck')],
            },
        ),
        migrations.CreateModel(
            name='OrganismCommandReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(max_length=64)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('request_reference', models.CharField(max_length=128)),
                ('payload_fingerprint', models.CharField(max_length=64)),
                ('authority_decision_reference', models.CharField(max_length=71)),
                ('lineage_reference', models.CharField(max_length=71, unique=True)),
                ('result_payload', models.JSONField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organism_command_receipts', to='core.identity')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('actor', 'action', 'idempotency_key'), name='s015_command_receipt_idem_uniq')],
            },
        ),
        migrations.AddConstraint(
            model_name='organismmembership',
            constraint=models.UniqueConstraint(fields=('identity', 'living_organism'), name='s015_identity_organism_membership_uniq'),
        ),
        migrations.AddConstraint(
            model_name='organismroledefinition',
            constraint=models.UniqueConstraint(fields=('living_organism', 'code', 'definition_version'), name='s015_role_definition_version_uniq'),
        ),
        migrations.RunPython(
            install_s015_postgresql_guardians,
            remove_s015_postgresql_guardians,
        ),
    ]
